import os

EMBEDDING_MODEL_DEPLOYMENT_NAME = os.environ.get("EMBEDDING_MODEL_DEPLOYMENT_NAME")
COGNITIVE_SEARCH_API_KEY = os.environ.get("COGNITIVE_SEARCH_API_KEY")
COGNITIVE_SEARCH_ENDPOINT = os.environ.get("COGNITIVE_SEARCH_ENDPOINT")
COGNITIVE_SEARCH_INDEX = os.environ.get("COGNITIVE_SEARCH_INDEX")
AZURE_STORAGE_ACCOUNT = os.environ.get("AZURE_STORAGE_ACCOUNT")
AZURE_STORAGE_CONTAINER = os.environ.get("AZURE_STORAGE_CONTAINER")
